import assert from "node:assert/strict";
import test from "node:test";
import { AccessControl, DelimitedStatementParser, PlatformError, StatementImportService, TextStatementParser, XlsxStatementParser } from "../src/index.ts";

const setup = () => { const access = new AccessControl(); access.grant({ companyId: "company-a", userId: "owner-a", branchIds: new Set(["branch-a"]), active: true, permissions: new Set() }); access.grant({ companyId: "company-b", userId: "owner-b", branchIds: new Set(["branch-b"]), active: true, permissions: new Set() }); return { a: access.context("company-a", "branch-a", "owner-a", "session-a"), b: access.context("company-b", "branch-b", "owner-b", "session-b") }; };
const csv = "Date,Description,Debit,Credit,Reference\n01/08/2026,UPI received,,30000.00,UPI-1\n02/08/2026,Shop rent,12500.50,,RENT-1";
const textPdf = (rows: readonly string[]): string => { const stream = `BT\n/F1 12 Tf\n72 720 Td\n${rows.map((row, index) => `${index === 0 ? "" : "0 -18 Td\n"}(${row}) Tj`).join("\n")}\nET`; const objects = ["<< /Type /Catalog /Pages 2 0 R >>", "<< /Type /Pages /Kids [3 0 R] /Count 1 >>", "<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 5 0 R >> >> /MediaBox [0 0 612 792] /Contents 4 0 R >>", `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"]; let pdf = "%PDF-1.4\n"; const offsets = [0]; for (const [index, object] of objects.entries()) { offsets.push(pdf.length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; } const startXref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, "0")} 00000 n `).join("\n")}\ntrailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startXref}\n%%EOF\n`; return Buffer.from(pdf).toString("base64"); };
test("statement import normalizes Indian dates and amounts, retains sources and balances", async () => { const { a } = setup(); const service = new StatementImportService([new DelimitedStatementParser(), new TextStatementParser()]); const result = await service.import(a, { format: "csv", fileName: "icici.csv", content: csv }, { openingBalancePaise: 100000n, closingBalancePaise: 1849950n }); assert.equal(result.balanceStatus, "matched"); const transactions = service.transactionsFor(a, result.id); assert.equal(transactions[0]!.bookedOn, "2026-08-01"); assert.equal(transactions[0]!.creditPaise, 3000000n); assert.equal(transactions[1]!.debitPaise, 1250050n); assert.equal(transactions[1]!.sourceLocation, "row:3"); });
test("reimports and overlapping files never duplicate transactions", async () => { const { a } = setup(); const service = new StatementImportService(); const first = await service.import(a, { format: "csv", fileName: "first.csv", content: csv }); assert.equal((await service.import(a, { format: "csv", fileName: "same.csv", content: csv })).id, first.id); const overlapping = await service.import(a, { format: "csv", fileName: "overlap.csv", content: `${csv}\n03/08/2026,New credit,,5.00,UPI-2` }); assert.equal(service.transactionsFor(a, overlapping.id).length, 3); });
test("uncertain source rows and balance inconsistencies are retained for review and isolated", async () => { const { a, b } = setup(); const service = new StatementImportService(); const result = await service.import(a, { format: "csv", fileName: "uncertain.csv", content: "Date,Description,Debit,Credit\nnot-a-date,Unknown,,12" }, { openingBalancePaise: 0n, closingBalancePaise: 12n }); assert.equal(result.balanceStatus, "mismatch"); assert.equal(result.reviewReasons.length, 2); assert.throws(() => service.get(b, result.id), (error: unknown) => error instanceof PlatformError && error.code === "TENANT_ISOLATION"); });
test("native Excel parser requires a base64 workbook and reports an empty workbook without posting", async () => { const { a } = setup(); const service = new StatementImportService([new XlsxStatementParser()]); await assert.rejects(service.import(a, { format: "xlsx", fileName: "invalid.xlsx", content: Buffer.from("not a workbook").toString("base64") })); });
test("text-based PDF statements are extracted without automatic ledger posting", async () => { const { a } = setup(); const service = new StatementImportService(); const result = await service.import(a, { format: "pdf", fileName: "icici.pdf", content: textPdf(["01/08/2026 | UPI received | | 30000.00 | UPI-1", "02/08/2026 | Shop rent | 12500.50 | | RENT-1"]) }); const transactions = service.transactionsFor(a, result.id); assert.equal(transactions.length, 2); assert.equal(transactions[0]!.creditPaise, 3000000n); assert.equal(transactions[1]!.debitPaise, 1250050n); });
