/**
 * Issue #191 — the e-way bill page a driver is handed, printed from what the portal gave us.
 *
 * Two things decide everything in this file, and they pull in opposite directions.
 *
 *  1. **CGST Rule 138A(1) does not ask for this page.** The person in charge of the vehicle must
 *     carry the invoice, bill of supply or delivery challan, and *either* a copy of the e-way bill
 *     in physical form *or* the e-way bill number in electronic form. The number alone is enough in
 *     law. So nothing in the product may be blocked, held or refused because this page was not
 *     printed.
 *  2. **Every driver in India carries the printed page anyway**, and officers at check posts expect
 *     it. That makes printing it a convention worth supporting properly rather than half-way.
 *
 * Which is why this page is not one of our designs. It is the portal's own page: its five sections,
 * in its order, under its headings, in its words. An officer reads these headings to find a field,
 * and a prettier arrangement of them is a worse document. Nothing on it is composed by us — no QR
 * square, no barcode, no "generated by" line of our own — because every value on a government
 * document has to be the government's or the consignor's, never the software's.
 */
import { readPortalTimestamp } from '../../transport/src/validity.ts';
import type {
  ConsignmentDocument,
  ConsignmentLine,
  EwayBillRecord,
  Movement,
  MovementParty,
  MovementReason,
  TransportMode,
} from '../../transport/src/types.ts';
import { escapeHtml } from './parts.ts';
import { qrSvg } from './qr.ts';

export interface EwayPrintOptions {
  /** Now, for deciding whether a bill whose validity has run out prints as expired. */
  readonly now?: Date;
  /**
   * The QR square's content **exactly as the provider's response gave it**.
   *
   * Left out when the provider gave none, and then no QR is drawn and no empty box stands in for
   * it. A QR code on a government document that we composed ourselves would scan to something the
   * portal never said.
   */
  readonly qrContent?: string | null;
}

/** The portal's own words for why goods are moving. */
const SUB_SUPPLY_NAMES: Readonly<Record<MovementReason, string>> = Object.freeze({
  SUPPLY: 'Supply',
  IMPORT: 'Import',
  EXPORT: 'Export',
  JOB_WORK: 'Job Work',
  FOR_OWN_USE: 'For Own Use',
  EXHIBITION_OR_FAIRS: 'Exhibition or Fairs',
  LINE_SALES: 'Line Sales',
  SALES_RETURN: 'Sales Return',
  BRANCH_TRANSFER: 'Branch Transfer',
  SKD_CKD: 'SKD/CKD',
  OTHERS: 'Others',
});

const MODE_NAMES: Readonly<Record<TransportMode, string>> = Object.freeze({
  ROAD: 'Road',
  RAIL: 'Rail',
  AIR: 'Air',
  SHIP: 'Ship',
  NON_MOTORISED: 'Non-motorised',
});

const DOCUMENT_NAMES: Readonly<Record<ConsignmentDocument['documentType'], string>> = Object.freeze({
  TAX_INVOICE: 'Tax invoice',
  BILL_OF_SUPPLY: 'Bill of supply',
  DELIVERY_CHALLAN: 'Delivery challan',
  CREDIT_NOTE: 'Credit note',
  BILL_OF_ENTRY: 'Bill of entry',
});

/** IST is UTC+5:30, with no daylight saving, ever. */
const IST_OFFSET_MINUTES = 330;

/**
 * A moment as this page writes it: "22/03/2026 04:35 PM", Indian wall-clock.
 *
 * The record holds two shapes — the portal's own "DD/MM/YYYY HH:mm:ss" and our ISO instants — and
 * `readPortalTimestamp` reads both, so a date on this page is never a reformat of a string whose
 * shape we guessed at.
 */
const moment = (raw: string | undefined): string => {
  if (raw === undefined || raw.trim() === '') return '';
  const at = readPortalTimestamp(raw);
  if (Number.isNaN(at.getTime())) return '';
  const indian = new Date(at.getTime() + IST_OFFSET_MINUTES * 60_000);
  const pad = (value: number): string => String(value).padStart(2, '0');
  const hour24 = indian.getUTCHours();
  const hour12 = hour24 % 12 === 0 ? 12 : hour24 % 12;
  return `${pad(indian.getUTCDate())}/${pad(indian.getUTCMonth() + 1)}/${indian.getUTCFullYear()} ${pad(hour12)}:${pad(indian.getUTCMinutes())} ${hour24 < 12 ? 'AM' : 'PM'}`;
};

/** "2026-03-22" the way every field on this page carries a date: 22/03/2026. */
const day = (isoDay: string): string => isoDay.split('-').reverse().join('/');

/** Paise as this page writes money: plain, two decimals, no symbol and no grouping — the portal's way. */
const amount = (paise: bigint): string => {
  const negative = paise < 0n;
  const absolute = negative ? -paise : paise;
  return `${negative ? '-' : ''}${absolute / 100n}.${String(absolute % 100n).padStart(2, '0')}`;
};

/** The rate a line's tax works out to, as the portal prints it: two decimals. */
const rate = (taxPaise: bigint, taxableValuePaise: bigint): string => {
  if (taxableValuePaise === 0n) return '0.00';
  // Basis points first, so the division is integer and the rounding is ours rather than a float's.
  return (Number((taxPaise * 10_000n) / taxableValuePaise) / 100).toFixed(2);
};

/**
 * The portal's tax-rate column: `9.00+9.00+0.00+0.00+0.00`.
 *
 * The five are CGST, SGST, IGST, Cess and Cess Non-Advol, in that order. We hold no non-advalorem
 * cess — it is charged per unit rather than as a percentage — so its place is filled with 0.00
 * rather than dropped, because a four-part string under a five-part heading is read wrongly.
 */
const rateString = (line: ConsignmentLine): string =>
  [
    rate(line.cgstPaise, line.taxableValuePaise),
    rate(line.sgstPaise, line.taxableValuePaise),
    rate(line.igstPaise, line.taxableValuePaise),
    rate(line.cessPaise, line.taxableValuePaise),
    '0.00',
  ].join('+');

const linesOf = (movement: Movement): readonly ConsignmentLine[] =>
  movement.documents.flatMap((document) => document.lines);

const totalsOf = (lines: readonly ConsignmentLine[]) =>
  lines.reduce(
    (total, line) => ({
      taxableValuePaise: total.taxableValuePaise + line.taxableValuePaise,
      cgstPaise: total.cgstPaise + line.cgstPaise,
      sgstPaise: total.sgstPaise + line.sgstPaise,
      igstPaise: total.igstPaise + line.igstPaise,
      cessPaise: total.cessPaise + line.cessPaise,
    }),
    { taxableValuePaise: 0n, cgstPaise: 0n, sgstPaise: 0n, igstPaise: 0n, cessPaise: 0n },
  );

/**
 * Why this e-way bill cannot be printed, in plain words, or `null` when it can.
 *
 * A page is printed only once the portal has answered with a number. Printing anything before that
 * would put a document in a driver's hand that no government record stands behind, which is the one
 * mistake this whole lane exists to prevent. The offline Part A file is the honest answer for that
 * moment, and it says inside itself that it is not an e-way bill.
 */
export const ewayPrintRefusal = (record: EwayBillRecord): string | null => {
  if (record.acknowledgement === undefined) {
    return record.status === 'NOT_REQUIRED'
      ? 'These goods need no e-way bill, so there is no e-way bill to print.'
      : 'The portal has not given an e-way bill number for this movement yet, so there is nothing to print. The goods may not move on a page we printed ourselves.';
  }
  return null;
};

/** The heavy line across the top, when this e-way bill is not one the goods may simply travel on. */
const banner = (record: EwayBillRecord, options: EwayPrintOptions): string => {
  if (record.status === 'CANCELLED') {
    const at = moment(record.cancelledAt);
    return `CANCELLED${at === '' ? '' : ` on ${at}`}`;
  }
  if (record.status === 'REJECTED') {
    const at = moment(record.rejectedAt);
    return `REJECTED by the other party${at === '' ? '' : ` on ${at}`}`;
  }
  const validUntil = record.acknowledgement?.validUntil;
  const now = options.now;
  const runOut =
    record.status === 'EXPIRED' ||
    (validUntil !== undefined && now !== undefined && readPortalTimestamp(validUntil).getTime() <= now.getTime());
  if (runOut && validUntil !== undefined) return `EXPIRED at ${moment(validUntil)}`;
  if (record.status === 'PART_A_ONLY') return 'PART-B NOT ENTERED — the goods may not move on this e-way bill yet';
  return '';
};

const row = (label: string, value: string): string =>
  `<tr><th>${escapeHtml(label)}</th><td>${escapeHtml(value)}</td></tr>`;

const addressBlock = (heading: string, party: MovementParty, addressLabel: string, address: MovementParty): string => `
  <td class="party">
    <div class="party-head">${escapeHtml(heading)}</div>
    <table class="pairs">
      ${row('GSTIN', party.gstin)}
      ${row('Legal Name', party.legalName)}
      ${row('State Code', party.stateCode)}
    </table>
    <div class="party-sub">${escapeHtml(addressLabel)}</div>
    <div class="address">${[address.address1, address.address2 ?? '', address.place, address.pincode]
      .filter((part) => part.trim() !== '')
      .map((part) => escapeHtml(part))
      .join(', ')}</div>
  </td>`;

/**
 * One e-way bill, on A4, as the portal's own page.
 *
 * `record` is what the portal told us; `movement` is what was on the lorry. Nothing is re-derived
 * from the invoice, because the page has to say what the e-way bill says even when a later
 * correction has moved the bill on.
 */
export const renderEwayBill = (record: EwayBillRecord, movement: Movement, options: EwayPrintOptions = {}): string => {
  const refusal = ewayPrintRefusal(record);
  if (refusal !== null) throw new Error(refusal);
  const acknowledgement = record.acknowledgement as NonNullable<EwayBillRecord['acknowledgement']>;

  const primary = movement.documents[0];
  const lines = linesOf(movement);
  const totals = totalsOf(lines);
  const totalInvoicePaise =
    totals.taxableValuePaise + totals.cgstPaise + totals.sgstPaise + totals.igstPaise + totals.cessPaise;
  const inward = movement.reason === 'SALES_RETURN' || movement.reason === 'IMPORT';
  const from = movement.dispatchFrom ?? movement.consignor;
  const to = movement.shipTo ?? movement.billTo;
  const top = banner(record, options);

  const details = `
    <h2>E-Way Bill Details</h2>
    <table class="pairs wide">
      ${row('E-Way Bill No.', acknowledgement.ewayBillNumber)}
      ${row('Generated Date', moment(acknowledgement.generatedAt))}
      ${row('Generated By', `${movement.consignor.gstin} — ${movement.consignor.legalName}`)}
      ${row('Valid Upto', acknowledgement.validUntil === undefined ? 'Not started — no vehicle on this e-way bill yet' : moment(acknowledgement.validUntil))}
      ${row('Mode', MODE_NAMES[movement.transportMode])}
      ${row('Approx Distance', record.distanceKm === undefined ? '' : `${record.distanceKm} KM`)}
      ${row('Type', `${inward ? 'Inward' : 'Outward'}-${SUB_SUPPLY_NAMES[movement.reason]}`)}
      ${row(
        'Document Details',
        primary === undefined
          ? `${record.documentNumber}-${day(record.documentDate)}`
          : `${DOCUMENT_NAMES[primary.documentType]}-${primary.documentNumber}-${day(primary.documentDate)}`,
      )}
      ${row('Transaction Type', movement.shipTo === undefined ? 'Regular' : 'Bill To - Ship To')}
    </table>`;

  const addresses = `
    <h2>Address Details</h2>
    <table class="addresses"><tr>
      ${addressBlock('From', movement.consignor, 'Dispatch From', from)}
      ${addressBlock('To', movement.billTo, 'Ship To', to)}
    </tr></table>`;

  const goods = `
    <h2>Goods Details</h2>
    <table class="goods fixed">
      <thead><tr>
        <th style="width:14%">HSN Code</th>
        <th style="width:30%">Product Name &amp; Desc.</th>
        <th class="num" style="width:13%">Quantity</th>
        <th class="num" style="width:17%">Taxable Amount Rs.</th>
        <th class="num" style="width:26%">Tax Rate (C+S+I+Cess+Cess Non.Advol)</th>
      </tr></thead>
      <tbody>${lines
        .map(
          (line) => `<tr>
        <td>${escapeHtml(line.hsnCode)}</td>
        <td class="anywhere">${escapeHtml(line.description)}</td>
        <td class="num">${escapeHtml(`${line.quantity} ${line.unit}`)}</td>
        <td class="num">${escapeHtml(amount(line.taxableValuePaise))}</td>
        <td class="num rate">${escapeHtml(rateString(line))}</td>
      </tr>`,
        )
        .join('')}</tbody>
    </table>
    <table class="pairs wide totals">
      ${row('Total Taxable Amount', amount(totals.taxableValuePaise))}
      ${row('CGST Amount', amount(totals.cgstPaise))}
      ${row('SGST Amount', amount(totals.sgstPaise))}
      ${row('IGST Amount', amount(totals.igstPaise))}
      ${row('CESS Amount', amount(totals.cessPaise))}
      ${row('CESS Non.Advol Amount', '0.00')}
      ${row('Other Amount', '0.00')}
      ${row('Total Invoice Amount', amount(totalInvoicePaise))}
    </table>`;

  const transporter = movement.transporter ?? record.transporter;
  const transportation = `
    <h2>Transportation Details</h2>
    <table class="pairs wide">
      ${row('Transporter ID & Name', transporter === undefined ? '' : `${transporter.transporterId} — ${transporter.name}`)}
      ${row(
        'Transporter Doc. No. & Date',
        transporter?.documentNumber === undefined
          ? ''
          : `${transporter.documentNumber}${transporter.documentDate === undefined ? '' : ` — ${day(transporter.documentDate)}`}`,
      )}
    </table>`;

  const vehicles = `
    <h2>Vehicle Details</h2>
    <table class="goods">
      <thead><tr>
        <th>Mode</th>
        <th>Vehicle / Trans Doc No. &amp; Dt.</th>
        <th>From</th>
        <th>Entered Date</th>
        <th>Entered By</th>
        <th>CEWB No.</th>
        <th>Multi Veh. Info.</th>
      </tr></thead>
      <tbody>${
        record.vehicleLegs.length === 0
          ? '<tr><td colspan="7">No vehicle has been entered on this e-way bill.</td></tr>'
          : record.vehicleLegs
              .map(
                (leg) => `<tr>
        <td>${escapeHtml(MODE_NAMES[leg.mode])}</td>
        <td>${escapeHtml(leg.registrationNumber)}</td>
        <td>${escapeHtml(leg.fromPlace)}</td>
        <td>${escapeHtml(moment(leg.recordedAt))}</td>
        <td>${escapeHtml(movement.consignor.gstin)}</td>
        <td>${escapeHtml(record.consolidatedTripNumber ?? '')}</td>
        <td></td>
      </tr>`,
              )
              .join('')
      }</tbody>
    </table>`;

  // Drawn only from the provider's own response. No response, no square, and no placeholder box in
  // its place: this is the government's document, not our layout.
  const qr =
    options.qrContent === undefined || options.qrContent === null || options.qrContent.trim() === ''
      ? ''
      : `<div class="qr">${qrSvg(options.qrContent, `E-way bill ${acknowledgement.ewayBillNumber}`)}</div>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(`E-Way Bill ${acknowledgement.ewayBillNumber}`)}</title>
<style>${styles()}</style>
</head>
<body>
<div class="sheet" data-eway="${escapeHtml(acknowledgement.ewayBillNumber)}" data-status="${escapeHtml(record.status)}">
  <div class="sheet-head">
    <h1>e-Way Bill</h1>
    ${qr}
  </div>
  ${top === '' ? '' : `<div class="banner">${escapeHtml(top)}</div>`}
  ${details}
  ${addresses}
  ${goods}
  ${transportation}
  ${vehicles}
</div>
</body>
</html>`;
};

/**
 * The page's own stylesheet.
 *
 * Deliberately not the invoice's: a bill carries the business's colours and its mark, and this page
 * carries neither. It is a government form, printed plainly, and a business that brands it has made
 * its own document out of the portal's.
 */
const styles = (): string => `
  :root { color-scheme: light; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #f4f4f4; font-family: Arial, Helvetica, sans-serif; font-size: 9.5pt; color: #000; line-height: 1.35; }
  .sheet { width: 210mm; max-width: calc(100% - 24px); margin: 12px auto; background: #fff; padding: 10mm; box-shadow: 0 1px 4px rgba(0,0,0,.18); }
  .sheet-head { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #000; padding-bottom: 2mm; }
  h1 { font-size: 15pt; margin: 0; letter-spacing: .04em; }
  h2 { font-size: 10pt; margin: 4mm 0 1.5mm; text-transform: uppercase; letter-spacing: .05em; border-bottom: 1px solid #000; padding-bottom: .8mm; }
  .banner { margin-top: 2.5mm; border: 2px solid #000; padding: 2mm; font-weight: 700; text-align: center; letter-spacing: .03em; }
  table { width: 100%; border-collapse: collapse; }
  .pairs th { width: 38%; text-align: left; font-weight: 600; vertical-align: top; padding: 1mm 1.5mm; }
  .pairs td { padding: 1mm 1.5mm; vertical-align: top; overflow-wrap: anywhere; }
  .pairs.wide th { width: 30%; }
  .pairs.wide th, .pairs.wide td, .goods th, .goods td { border: 1px solid #000; }
  .totals { margin-top: 2mm; }
  .addresses { table-layout: fixed; }
  .addresses td.party { border: 1px solid #000; padding: 2mm; vertical-align: top; width: 50%; }
  .party-head { font-weight: 700; margin-bottom: 1mm; }
  .party-sub { font-weight: 600; margin-top: 1.5mm; }
  .address { overflow-wrap: anywhere; }
  .goods.fixed { table-layout: fixed; }
  .goods th { text-align: left; padding: 1.2mm 1.5mm; font-weight: 600; }
  .goods td { padding: 1.2mm 1.5mm; vertical-align: top; overflow-wrap: break-word; }
  /* A name a shopkeeper typed may be one long word; a rate string never breaks, because a driver
     reading "0.00+0.00+18.00+0." over two lines cannot tell which tax is which. */
  .goods td.anywhere { overflow-wrap: anywhere; }
  .goods td.rate { white-space: nowrap; }
  .num { text-align: right; font-variant-numeric: tabular-nums; }
  .qr { width: 28mm; height: 28mm; }
  @media print {
    body { background: #fff; }
    .sheet { margin: 0; box-shadow: none; width: auto; max-width: none; padding: 0; }
    @page { size: A4; margin: 10mm; }
  }
`;
