// Reading a GST e-invoice JSON file (issue #15).
//
// This is the happy path: the document is structured, was generated by the supplier's
// own system and, when it carries an IRN, has been registered with the Invoice
// Registration Portal. Fields read from it get confidence 1 and cite their JSON path,
// so the reviewer can see exactly where each number came from. Nothing is inferred: a
// field that is absent stays absent.

import { validateGstin } from "../../masters/src/validation.ts";
import type { IsoDate, Paise } from "../../masters/src/types.ts";
import { rupeesToPaise } from "./money.ts";
import type { ExtractedField, ExtractedLine } from "./inbox-types.ts";

export interface EInvoiceReadResult {
  readonly ok: boolean;
  readonly problems: readonly string[];
  readonly supplierGstin?: ExtractedField<string>;
  readonly supplierName?: ExtractedField<string>;
  readonly buyerGstin?: ExtractedField<string>;
  readonly invoiceNumber?: ExtractedField<string>;
  readonly invoiceDate?: ExtractedField<IsoDate>;
  readonly taxableValuePaise?: ExtractedField<Paise>;
  readonly totalTaxPaise?: ExtractedField<Paise>;
  readonly invoiceTotalPaise?: ExtractedField<Paise>;
  readonly irn?: ExtractedField<string>;
  readonly lines: readonly ExtractedLine[];
  /** Every GST number the file names, so routing can spot a document meant for someone else. */
  readonly allGstins: readonly string[];
}

const field = <T>(value: T, jsonPath: string, text: string): ExtractedField<T> => ({ value, confidence: 1, evidence: { page: 0, text, jsonPath } });

const at = (source: unknown, path: string): unknown => path.split(".").reduce<unknown>((node, part) => (node && typeof node === "object" ? (node as Record<string, unknown>)[part] : undefined), source);

const text = (source: unknown, path: string): string | undefined => {
  const value = at(source, path);
  return typeof value === "string" && value.trim() ? value.trim() : typeof value === "number" ? String(value) : undefined;
};

const money = (source: unknown, path: string): ExtractedField<Paise> | undefined => {
  const value = at(source, path);
  if (typeof value !== "number" && typeof value !== "string") return undefined;
  const paise = rupeesToPaise(value);
  return paise === null ? undefined : field(paise, path, String(value));
};

/** e-invoice dates are DD/MM/YYYY. Anything else is reported rather than reinterpreted. */
export function parseEInvoiceDate(raw: string): IsoDate | null {
  const match = /^(\d{2})\/(\d{2})\/(\d{4})$/.exec(raw.trim());
  if (!match) return null;
  const [, day = "", month = "", year = ""] = match;
  const iso = `${year}-${month}-${day}`;
  const parsed = new Date(`${iso}T00:00:00Z`);
  if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== iso) return null;
  return iso;
}

export function readEInvoiceJson(raw: string): EInvoiceReadResult {
  const problems: string[] = [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return { ok: false, problems: ["This file is not readable JSON."], lines: [], allGstins: [] };
  }
  // Signed responses from the portal wrap the invoice; unsigned files are the invoice.
  const document = (at(parsed, "DocDtls") ? parsed : at(parsed, "Data") ?? at(parsed, "data") ?? parsed) as Record<string, unknown>;
  if (!at(document, "DocDtls.No")) return { ok: false, problems: ["This JSON file does not look like a GST e-invoice: it has no document details."], lines: [], allGstins: [] };

  const supplierGstinRaw = text(document, "SellerDtls.Gstin");
  const buyerGstinRaw = text(document, "BuyerDtls.Gstin");
  for (const [label, value] of [["supplier", supplierGstinRaw], ["buyer", buyerGstinRaw]] as const) {
    if (value && !validateGstin(value).ok) problems.push(`The ${label} GST number in this file (${value}) is not a valid GST number.`);
  }
  const dateRaw = text(document, "DocDtls.Dt");
  const invoiceDate = dateRaw ? parseEInvoiceDate(dateRaw) : null;
  if (dateRaw && !invoiceDate) problems.push(`The invoice date in this file (${dateRaw}) is not in the DD/MM/YYYY form an e-invoice uses.`);

  const rawLines = at(document, "ItemList");
  const lines: ExtractedLine[] = (Array.isArray(rawLines) ? rawLines : []).map((line, index) => {
    const base = `ItemList[${index}]`;
    const description = text(line, "PrdDesc") ?? "";
    const gstRate = at(line, "GstRt");
    return {
      description: field(description, `${base}.PrdDesc`, description),
      ...(text(line, "HsnCd") ? { hsnSac: field(text(line, "HsnCd") as string, `${base}.HsnCd`, text(line, "HsnCd") as string) } : {}),
      ...(text(line, "Qty") ? { quantity: field(text(line, "Qty") as string, `${base}.Qty`, text(line, "Qty") as string) } : {}),
      ...(text(line, "Unit") ? { unit: field(text(line, "Unit") as string, `${base}.Unit`, text(line, "Unit") as string) } : {}),
      ...(money(line, "UnitPrice") ? { ratePaise: money(line, "UnitPrice") as ExtractedField<Paise> } : {}),
      ...(money(line, "AssAmt") ? { taxableValuePaise: money(line, "AssAmt") as ExtractedField<Paise> } : {}),
      ...(typeof gstRate === "number" ? { gstRateBasisPoints: field(Math.round(gstRate * 100), `${base}.GstRt`, String(gstRate)) } : {}),
    };
  });

  const cgst = money(document, "ValDtls.CgstVal");
  const sgst = money(document, "ValDtls.SgstVal");
  const igst = money(document, "ValDtls.IgstVal");
  const cess = money(document, "ValDtls.CesVal");
  const taxParts = [cgst, sgst, igst, cess].filter((part): part is ExtractedField<Paise> => part !== undefined);
  const totalTax = taxParts.length === 0 ? undefined : field(taxParts.reduce((sum, part) => sum + part.value, 0n), "ValDtls.CgstVal+SgstVal+IgstVal+CesVal", taxParts.map((part) => part.evidence.text).join(" + "));

  const irnRaw = text(document, "Irn") ?? text(parsed, "Irn");
  return {
    ok: problems.length === 0,
    problems,
    ...(supplierGstinRaw ? { supplierGstin: field(supplierGstinRaw, "SellerDtls.Gstin", supplierGstinRaw) } : {}),
    ...(text(document, "SellerDtls.LglNm") ? { supplierName: field(text(document, "SellerDtls.LglNm") as string, "SellerDtls.LglNm", text(document, "SellerDtls.LglNm") as string) } : {}),
    ...(buyerGstinRaw ? { buyerGstin: field(buyerGstinRaw, "BuyerDtls.Gstin", buyerGstinRaw) } : {}),
    ...(text(document, "DocDtls.No") ? { invoiceNumber: field(text(document, "DocDtls.No") as string, "DocDtls.No", text(document, "DocDtls.No") as string) } : {}),
    ...(invoiceDate ? { invoiceDate: field(invoiceDate, "DocDtls.Dt", dateRaw as string) } : {}),
    ...(money(document, "ValDtls.AssVal") ? { taxableValuePaise: money(document, "ValDtls.AssVal") as ExtractedField<Paise> } : {}),
    ...(totalTax ? { totalTaxPaise: totalTax } : {}),
    ...(money(document, "ValDtls.TotInvVal") ? { invoiceTotalPaise: money(document, "ValDtls.TotInvVal") as ExtractedField<Paise> } : {}),
    ...(irnRaw ? { irn: field(irnRaw, "Irn", irnRaw) } : {}),
    allGstins: [supplierGstinRaw, buyerGstinRaw].filter((value): value is string => Boolean(value)),
    lines,
  };
}
